import React, { useState } from 'react';
import { Journal } from '../../services/api';

interface JournalListProps {
  journals: Journal[];
  activeJournalId: string | null;
  onSelectJournal: (id: string) => void;
  onNewJournalClick: () => void;
  selectedTag: string | null;
  onSelectTag: (tag: string | null) => void;
}

export const JournalSidebar: React.FC<JournalListProps> = ({
  journals,
  activeJournalId,
  onSelectJournal,
  onNewJournalClick,
  selectedTag,
  onSelectTag,
}) => {
  const [searchTerm, setSearchTerm] = useState('');

  // Extract all unique tags generated by Gemini
  const allTags = Array.from(
    new Set(journals.flatMap(j => j.analysis?.keywords || []))
  );

  const filteredJournals = journals.filter(j => {
    const matchSearch = j.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
      j.content.toLowerCase().includes(searchTerm.toLowerCase());
    const matchTag = selectedTag ? j.analysis?.keywords?.includes(selectedTag) : true;
    return matchSearch && matchTag;
  });

  return (
    <aside className="sidebar-panel">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <h3 style={{ fontSize: '1.1rem', fontWeight: 700 }}>Personal Logs</h3>
        <button className="btn btn-primary" onClick={onNewJournalClick} style={{ padding: '0.4rem 0.8rem', fontSize: '0.85rem' }}>
          + New Entry
        </button>
      </div>

      <input
        type="text"
        placeholder="🔍 Search journals..."
        value={searchTerm}
        onChange={(e) => setSearchTerm(e.target.value)}
        className="text-input"
        style={{ padding: '0.5rem 0.75rem', fontSize: '0.85rem' }}
      />

      {allTags.length > 0 && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
          <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
            AI Semantic Tags
          </div>
          <div className="badge-row" style={{ maxHeight: '70px', overflowY: 'auto' }}>
            <span 
              className={`badge ${selectedTag === null ? 'mood-badge' : ''}`}
              style={{ cursor: 'pointer' }}
              onClick={() => onSelectTag(null)}
            >
              All
            </span>
            {allTags.map(tag => (
              <span
                key={tag}
                className={`badge ${selectedTag === tag ? 'mood-badge' : ''}`}
                style={{ cursor: 'pointer' }}
                onClick={() => onSelectTag(selectedTag === tag ? null : tag)}
              >
                #{tag}
              </span>
            ))}
          </div>
        </div>
      )}

      <div className="journal-list">
        {filteredJournals.length === 0 ? (
          <div style={{ color: 'var(--text-muted)', fontSize: '0.85rem', textAlign: 'center', marginTop: '2rem' }}>
            No journal entries found.
          </div>
        ) : (
          filteredJournals.map(item => (
            <div
              key={item.id}
              className={`journal-item ${item.id === activeJournalId ? 'active' : ''}`}
              onClick={() => onSelectJournal(item.id)}
            >
              <div className="journal-item-title">{item.title}</div>
              <div className="journal-item-meta">
                <span>{new Date(item.createdAt).toLocaleDateString('en-US')}</span>
                {item.analysis?.mood && (
                  <span style={{ color: 'var(--accent-purple)', fontWeight: 600 }}>
                    {item.analysis.mood}
                  </span>
                )}
              </div>
            </div>
          ))
        )}
      </div>
    </aside>
  );
};
